import argparse

parser = argparse.ArgumentParser()

def wiki_cooc():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='AHGFC', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=1000, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=64, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=32, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=1024, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=32, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=64, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=32, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=5000, help='')
    parser.add_argument('--lr', type=float, default=0.01, help='')
    parser.add_argument('--weight_decay', type=float, default=0.1, help='')
    parser.add_argument('--cuda_device', type=int, default=0, help='')
    parser.add_argument('--use_cuda', type=bool, default=True, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2024, help='')
    # loss weight
    parser.add_argument('--Weight_loss_re_x', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_re_x_mse', type=float, default=0.0, help='')
    parser.add_argument('--Weight_loss_re_a', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_kl_g', type=float, default=0.0, help='')
    args = parser.parse_args()
    return args

def minesweeper():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='AHGFC', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=1000, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=64, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=32, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=1024, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=32, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=64, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=32, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=6, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=5000, help='')
    parser.add_argument('--lr', type=float, default=0.001, help='')
    parser.add_argument('--weight_decay', type=float, default=0.1, help='')
    parser.add_argument('--cuda_device', type=int, default=0, help='')
    parser.add_argument('--use_cuda', type=bool, default=True, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2024, help='')
    # loss weight
    parser.add_argument('--Weight_loss_re_x', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_re_x_mse', type=float, default=0.0, help='')
    parser.add_argument('--Weight_loss_re_a', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_kl_g', type=float, default=1.0, help='')
    args = parser.parse_args()
    return args

def workers():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='AHGFC', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=1000, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=64, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=32, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=1024, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=32, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=64, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=32, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=6, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=5000, help='')
    parser.add_argument('--lr', type=float, default=0.001, help='')
    parser.add_argument('--weight_decay', type=float, default=0.01, help='')
    parser.add_argument('--cuda_device', type=int, default=0, help='')
    parser.add_argument('--use_cuda', type=bool, default=True, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2024, help='')
    # loss weight
    parser.add_argument('--Weight_loss_re_x', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_re_x_mse', type=float, default=0.0, help='')
    parser.add_argument('--Weight_loss_re_a', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_kl_g', type=float, default=1.0, help='')
    args = parser.parse_args()
    return args


def acm():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='AHGFC', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=512, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=128, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=512, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=128, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=512, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=128, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=4, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=5000, help='')
    parser.add_argument('--lr', type=float, default=0.001, help='')
    parser.add_argument('--weight_decay', type=float, default=0.1, help='')
    parser.add_argument('--cuda_device', type=int, default=0, help='')
    parser.add_argument('--use_cuda', type=bool, default=True, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2024, help='')
    # loss weight
    parser.add_argument('--Weight_loss_re_x', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_re_x_mse', type=float, default=0.0, help='')
    parser.add_argument('--Weight_loss_re_a', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_kl_g', type=float, default=0.1, help='')
    args = parser.parse_args()
    return args

def texas():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='AHGFC', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=30, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=1024, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=64, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=128, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=64, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=1024, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=64, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=4, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=5000, help='')
    parser.add_argument('--lr', type=float, default=0.01, help='')
    parser.add_argument('--weight_decay', type=float, default=0.1, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2024, help='')
    # loss weight
    parser.add_argument('--Weight_loss_re_x', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_re_x_mse', type=float, default=0.0, help='')
    parser.add_argument('--Weight_loss_re_a', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_kl_g', type=float, default=1.0, help='')

    args = parser.parse_args()
    return args

def chameleon():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='AHGFC', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=512, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=64, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=512, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=64, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=512, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=64, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=4, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=5000, help='')
    parser.add_argument('--lr', type=float, default=0.01, help='')            # 固定lr=0.01
    parser.add_argument('--weight_decay', type=float, default=0.1, help='')   # 固定weight_decay = 0.1
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2024, help='')
    # loss weight
    parser.add_argument('--Weight_loss_re_x', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_re_x_mse', type=float, default=0.0, help='')
    parser.add_argument('--Weight_loss_re_a', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_kl_g', type=float, default=1.0, help='')
    args = parser.parse_args()
    return args

def dblp():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='AHGFC', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=300, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=256, help='hidden_dim_x') #有改动
    parser.add_argument('--output_dim_x', type=int, default=128, help='output_dim_x') #有改动
    parser.add_argument('--hidden_dim_a', type=int, default=256, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=128, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=256, help='hidden_dim_g')#有改动
    parser.add_argument('--output_dim_g', type=int, default=128, help='output_dim_g')#有改动
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=5000, help='')
    parser.add_argument('--lr', type=float, default=0.0005, help='')
    parser.add_argument('--weight_decay', type=float, default=5e-7, help='') # weight_decay=5e-5跑到过90.8
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2024, help='')
    # loss weight
    parser.add_argument('--Weight_loss_re_x', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_re_x_mse', type=float, default=0.0, help='')
    parser.add_argument('--Weight_loss_re_a', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_kl_g', type=float, default=1.0, help='')
    args = parser.parse_args()
    return args

def acm00():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='AHGFC', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=0, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=0, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=512, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=128, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=512, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=128, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=512, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=128, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=5000, help='')
    parser.add_argument('--lr', type=float, default=0.01, help='')
    parser.add_argument('--weight_decay', type=float, default=0.1, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    args = parser.parse_args()
    return args

def acm01():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='AHGFC', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=0, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=0, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=512, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=128, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=512, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=128, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=512, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=128, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=5000, help='')
    parser.add_argument('--lr', type=float, default=0.001, help='')
    parser.add_argument('--weight_decay', type=float, default=0.1, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    # loss weight
    parser.add_argument('--Weight_loss_re_x', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_re_x_mse', type=float, default=0.0, help='')
    parser.add_argument('--Weight_loss_re_a', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_kl_g', type=float, default=1.0, help='')
    args = parser.parse_args()
    return args

def acm02():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='AHGFC', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=0, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=0, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=512, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=128, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=512, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=128, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=512, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=128, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=5000, help='')
    parser.add_argument('--lr', type=float, default=0.001, help='')
    parser.add_argument('--weight_decay', type=float, default=0.1, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    # loss weight
    parser.add_argument('--Weight_loss_re_x', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_re_x_mse', type=float, default=0.0, help='')
    parser.add_argument('--Weight_loss_re_a', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_kl_g', type=float, default=1.0, help='')
    args = parser.parse_args()
    return args

def acm03():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='AHGFC', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=0, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=0, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=512, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=128, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=512, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=128, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=512, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=128, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=5000, help='')
    parser.add_argument('--lr', type=float, default=0.001, help='')
    parser.add_argument('--weight_decay', type=float, default=0.1, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    # loss weight
    parser.add_argument('--Weight_loss_re_x', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_re_x_mse', type=float, default=0.0, help='')
    parser.add_argument('--Weight_loss_re_a', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_kl_g', type=float, default=1.0, help='')
    args = parser.parse_args()
    return args

def acm04():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='AHGFC', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=0, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=0, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=512, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=128, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=512, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=128, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=512, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=128, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=5000, help='')
    parser.add_argument('--lr', type=float, default=0.01, help='')
    parser.add_argument('--weight_decay', type=float, default=0.1, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    # loss weight
    parser.add_argument('--Weight_loss_re_x', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_re_x_mse', type=float, default=0.0, help='')
    parser.add_argument('--Weight_loss_re_a', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_kl_g', type=float, default=1.0, help='')
    args = parser.parse_args()
    return args

def acm05():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_name', type=str, default='AHGFC', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=0, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=0, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=512, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=128, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=512, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=128, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=512, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=128, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=5000, help='')
    parser.add_argument('--lr', type=float, default=0.01, help='')
    parser.add_argument('--weight_decay', type=float, default=0.1, help='')
    parser.add_argument('--update_interval', type=int, default=10, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    # loss weight
    parser.add_argument('--Weight_loss_re_x', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_re_x_mse', type=float, default=0.0, help='')
    parser.add_argument('--Weight_loss_re_a', type=float, default=1.0, help='')
    parser.add_argument('--Weight_loss_kl_g', type=float, default=1.0, help='')
    args = parser.parse_args()
    return args


def get_settings(dataset='acm'):
    args_dic = {
        'workers': workers(),
        'minesweeper': minesweeper(),
        'wiki_cooc': wiki_cooc(),
        'acm': acm(),
        'dblp': dblp(),
        'texas': texas(),
        'chameleon': chameleon(),
        'acm00': acm00(),
        'acm01': acm01(),
        'acm02': acm02(),
        'acm03': acm03(),
        'acm04': acm04(),
        'acm05': acm05(),
    }
    return args_dic[dataset]
